export let movieNames = [
  "Abattoir",
  "Accident",
  "Adaptation",
  "Adoration",
  "Adventureland",
  "Afterschool",
  "Akira",
  "Aladdin",
  "Alexandria…Why?",
  "Ali",
  "Alice",
  "Alien",
  "Aliens",
  "Alléluia",
  "Alphaville",
  "Alps",
  "Amadeus",
  "Amarcord",
  "Amelie",
  "Amer",
  "Amistad",
  "Ammonite",
  "Amour",
  "Anaconda",
  "Angel-A",
  "Angst",
  "Anguish",
  "Annie",
  "Annihilation",
  "Anomalisa",
  "Ant-Man",
  "Antichrist",
  "Antiporno",
  "Antiviral",
  "Apostle",
  "Aquaman",
  "Archangel",
  "Archenemy",
  "Argo",
  "Ariel",
  "Armageddon",
  "Arrival",
  "Atonement",
  "Attenberg",
  "Audition",
  "Australia",
  "Ava",
  "Avatar",
  "About Schmidt",
  "About Time",
  "Ad Astra",
  "Adam Resurrected",
  "Adult World",
  "Aeon Flux",
  "After Hours",
  "Alien 3",
  "Alien: Covenant",
  "Alien: Resurrection",
  "Almayer’s Folly",
  "Almost Famous",
  "Always Shine",
  "American Animals",
  "American Beauty",
  "American Gangster",
  "American Gigolo",
  "American Graffiti",
  "American Honey",
  "American Hustle",
  "American Mary",
  "American Psycho",
  "Angel Heart",
  "Anna Christie",
  "Anna Karenina",
  "Annie Hall",
  "Another Earth",
  "Another Year",
  "Apocalypse Now",
  "Apt Pupil",
  "Ashik Kerib",
  "Assassin’s Creed",
  "Assassination Nation",
  "Atomic Blonde",
  "Auto Focus",
  "Autumn Sonata",
  "Avengers: Endgame",
  "Babe",
  "Badlands",
  "Ballast",
  "Bamboozled",
  "Baraka",
  "Barbarella",
  "Barfly",
  "Baskin",
  "Bastards",
  "Batman",
  "Cabaret",
  "Caddyshack",
  "Cake",
  "Calvaire",
  "Calvary",
  "Cam",
  "Candyman",
  "Capote",
  "Caravaggio",
  "Careful",
  "Carne",
  "Carol",
  "Carrie",
  "Carriers",
  "Cars",
  "Casablanca",
  "Casino",
  "Dagon",
  "Daguerréotypes",
  "Daisies",
  "Damnation",
  "Damsel",
  "Darlin’",
  "Daybreakers",
  "Face/Off",
  "Fantasia",
  "Fargo",
  "Faults",
  "Faust",
  "Faust",
  "Garage",
  "Gattaca",
  "Halloween",
  "Hamlet",
  "Hammett",
  "Hanagatami",
  "Hanna",
  "Happy-Go-Lucky",
  "Hardcore",
  "Hardware",
  "Haywire",
  "Jabberwocky",
  "Jackie",
  "Japón",
  "Jarhead",
  "Jauja",
  "Jaws",
  "Kafka",
  "Kagemusha",
  "Kamouraska",
  "Katzelmacher",
  "Labyrinth",
  "Laggies",
  "Lawless",
  "Maîtresse",
  "Macbeth",
  "Macbeth",
  "MacGruber",
  "Madadayo",
  "Maelström",
  "Magic",
  "Magnolia",
  "Maleficent",
  "Malina",
  "Malpertuis",
  "Mama",
  "Manderlay",
  "Mandy",
  "Manglehorn",
  "Manhattan",
  "Manhunter",
  "Maniac",
  "Mank",
  "Marnie",
  "Martha",
  "Martin",
  "Martyrs",
  "MASH",
  "Matador",
  "Matewan",
  "Mayhem",
  "Naked",
  "Naqoyquatsi",
  "Narc",
  "Nashville",
  "Paddington",
  "Pan",
  "Papillon",
  "Paprika",
  "Parasite",
  "Pariah",
  "Pasolini",
  "Passion",
  "Patagonia",
  "Paterson",
  "Paul",
  "Rampart",
  "Ran",
  "Rango",
  "Rashomon",
  "Ratcatcher",
  "Ravenous",
  "Raw",
  "Saboteur",
  "Safe",
  "Sakuran",
  "Salome",
  "Salvador",
  "Samsara",
  "Sanjuro",
  "Saraband",
  "Savages",
  "Saw",
  "Tabu",
  "Tampopo",
  "Tangerine",
  "Targets",
  "Vagabond",
  "Vampyr",
  "Walkabout",
  "Wall-E",
  "Wanda",
  "Warcraft",
  "Watchmen",
  "Xanadu",
  "Zama",
  "Zardoz",
  "A Beautiful Mind",
  "A Bigger Splash",
  "A Clockwork Orange",
  "A Dangerous Method",
  "A Ghost Story",
  "A Hidden Life",
  "A Mighty Heart",
  "A Monster Calls",
  "A Quiet Passion",
  "A Quiet Place",
  "A Safe Place",
  "A Scanner Darkly",
  "A Serious Man",
  "A Single Man",
  "A.I. Artificial Intelligence",
  "About a Boy",
  "Across the Universe",
  "After The Rehearsal",
  "Age of Consent",
  "Air Force One",
  "Alice in Wonderland",
  "Alita: Battle Angel",
  "All Is Lost",
  "All Monsters Attack",
  "All or Nothing",
  "All That Jazz",
  "All These Women",
  "Almanac of Fall",
  "American History X",
  "An Actor’s Revenge",
  "Antoine and Colette",
  "Any Given Sunday",
  "Artists and Models",
  "At Close Range",
  "Avengers: Infinity War",
  "Away From Her",
  "Away We Go",
  "Beast",
  "Blackhat",
  "BlacKkKlansman",
  "Blanche",
  "Blaze",
  "Braid",
  "Braveheart",
  "Brazil",
  "Changeling",
  "Chaplin",
  "Chappie",
  "Cracks",
  "Crash",
  "Deadpool",
  "Dean",
  "Dracula",
  "Ema",
  "Eraserhead",
  "Eva",
  "Frank",
  "Frankenstein",
  "Frankenweenie",
  "Frantz",
  "Gladiator",
  "Graduation",
  "Grass",
  "Gravity",
  "Head",
  "Heat",
  "Heathers",
  "Ida",
  "Images",
  "Keanu",
  "Kwaidan",
  "L’Avventura",
  "Meadowland",
  "Noah",
  "Platoon",
  "Roadgames",
  "Roadkill",
  "Scandal",
  "Scanners",
  "Scarecrow",
  "Scarface",
  "Seabiscuit",
  "Shadows",
  "Shame",
  "Shame",
  "Shazam!",
  "Slacker",
  "Stalker",
  "Starfish",
  "Starman",
  "Stay",
  "Swallow",
  "Tracks",
  "Traffic",
  "Trainspotting",
  "Trance",
  "Transcendence",
  "Uzak",
  "Byzantium",
  "Coraline",
  "Diva",
  "Dreams",
  "Dreams",
  "Emma.",
  "Equals",
  "Excalibur",
  "Freaks",
  "Freaky",
  "Gohatto",
  "Grease",
  "Häxan",
  "Kika",
  "Koyaanisqatsi",
  "Logan",
  "Lola",
  "Lola",
  "Melancholia",
  "Merantau",
  "Minari",
  "Nomadland",
  "Okja",
  "Orlando",
  "Pina",
  "Pleasantville",
  "Polar",
  "Powaqqatsi",
  "Re-Animator",
  "Relaxer",
  "Revanche",
  "Roma",
  "Roma",
  "Sebastiane",
  "Sicario",
  "Solaris",
  "Solaris",
  "Sugar",
  "Titane",
  "Titanic",
  "Unsane",
  "Viva",
  "A Bay of Blood",
  "A Cure For Wellness",
  "A Few Good Men",
  "A Field In England",
  "A Fistful Of Dollars",
  "A Fistful of Dynamite",
  "A Hard Days Night",
  "A History of Violence",
  "A Lesson In Love",
  "A Most Violent Year",
  "A Prairie Home Companion",
  "A Prayer Before Dawn",
  "A Summer at Grandpa’s",
  "A Swedish Love Story",
  "A Tale of Springtime",
  "A Very Long Engagement",
  "A Wrinkle In Time",
  "Ace In The Hole",
  "Ain’t Them Bodies Saints",
  "Alice in the Cities",
  "All About My Mother",
  "All The Real Girls",
  "An American In Paris",
  "An Elephant Sitting Still",
  "Anatomy of a Relationship",
  "And God Created Woman",
  "Annie Get Your Gun",
  "Ant-Man and the Wasp",
  "As Tears Go By",
  "Ashes Of Time Redux",
  "Assault on Precinct 13",
  "Au Revoir Les Enfants",
  "Avengers: Age of Ultron",
  "Baby Driver",
  "Bad Boys",
  "Bad Education",
  "Bad Lieutenant",
  "Barry Lyndon",
  "Barton Fink",
  "Basic Instinct",
  "Batman Begins",
  "Batman Forever",
  "Batman Returns",
  "Battle Royale",
  "Battleship Potemkin",
  "Caché (Hidden)",
  "Cairo Station",
  "Calamity Jane",
  "California Split",
  "Camera Buff",
  "Cape Fear",
  "Cape Fear",
  "Captain Fantastic",
  "Captain Marvel",
  "Captain Phillips",
  "Carlito’s Way",
  "Carnal Knowledge",
  "Carrie (2013)",
  "Casino Royale",
  "Castle Freak",
  "Cat People",
  "Cat People",
  "Catch 22",
  "Danger Diabolik",
  "Dangerous Beauty",
  "Dark City",
  "Dark Habits",
  "Dark Horse",
  "Dark River",
  "Dark Shadows",
  "Darkest Hour",
  "Das Boot",
  "Dating Amber",
  "Eastern Promises",
  "Easy Rider",
  "Eaux d’Artifice",
  "Faces Places",
  "Fahrenheit 451",
  "Fallen Angels",
  "Family Nest",
  "Family Plot",
  "Fast Color",
  "Fat City",
  "Fata Morgana",
  "Galaxy Quest",
  "Gangster Squad",
  "Hail Mary",
  "Hail, Caesar!",
  "Half Nelson",
  "Halloween (2018)",
  "Halloween 2",
  "Happy End",
  "Happy Together",
  "Hard Candy",
  "Hard Eight",
  "Haute Tension",
  "Jackie Brown",
  "Jacob’s Ladder",
  "Jakob’s Wife",
  "Jane Eyre",
  "Kamikaze Girls",
  "Katie Tippel",
  "La Collectionneuse",
  "La Haine",
  "La Jetée",
  "La Notte",
  "La Strada",
  "Lacombe, Lucien",
  "Lady Bird",
  "Lady Macbeth",
  "Lady Snowblood",
  "Lady Vengeance",
  "Land Ho!",
  "Last Days",
  "Lasting (Nieulotne)",
  "Laurence Anyways",
  "Layer Cake",
  "Mad Max",
  "Madame Bovary",
  "Madeline’s Madeline",
  "Magic Mike",
  "Magnificent Obsession",
  "Mala Noche",
  "Malcolm X",
  "Mamma Mia!",
  "Marathon Man",
  "Margin Call",
  "Marie Antoinette",
  "Marketa Lazarová",
  "Marriage Story",
  "Mars Attacks!",
  "Mary Poppins",
  "Masculin Fémenin",
  "Mata Hari",
  "Nacho Libre",
  "Naked Lunch",
  "Napoleon Dynamite",
  "Pacific Rim",
  "Paddington 2",
  "Paganini Horror",
  "Palm Springs",
  "Palo Alto",
  "Pan’s Labyrinth",
  "Pandora’s Box",
  "Panic Room",
  "Paper Moon",
  "Paradise Hills",
  "Paradise: Faith",
  "Paradise: Hope",
  "Paradise: Love",
  "Paris, Texas",
  "Pass Over",
  "Patty Hearst",
  "Pawn Sacrifice",
  "Rabbit’s Moon",
  "Rabid (2019)",
  "Raging Bull",
  "Raising Arizona",
  "Rampo Noir",
  "Saint Laurent",
  "Saint Maud",
  "Sanshiro Sugata",
  "Santa Sangre",
  "Satan’s Brew",
  "Satan’s Slaves",
  "Saw II",
  "Saw III",
  "Saw IV",
  "Saw V",
  "Saw VI",
  "Take Shelter",
  "Tamara Drewe",
  "Taxi Driver",
  "Valhalla Rising",
  "Vampire Circus",
  "Vampyros Lesbos",
  "Vanishing Point",
  "Vanishing Waves",
  "Variety Lights",
  "Waiting Women",
  "Waking Life",
  "War Horse",
  "War Requiem",
  "Water Lillies",
  "Wayne's World",
  "Buzzard",
  "Chicago",
  "Chinatown",
  "Collateral",
  "Contagion",
  "Container",
  "Depraved",
  "Despair",
  "Elena",
  "Foxcatcher",
  "Frida",
  "Furia",
  "Giliap",
  "Greta",
  "Isolation",
  "Jigsaw",
  "Leviathan",
  "Micmacs",
  "Mustang",
  "Nebraska",
  "Onibaba",
  "Predator",
  "Scream",
  "Selma",
  "Skyfall",
  "Spiral",
  "Submarine",
  "Subway",
  "Syriana",
  "Tesla",
  "Upgrade",
  "Vinyan",
  "Zodiac",
  "Zoolander",
  "A Cock and Bull Story",
  "A Date for Mad Mary",
  "A Hologram for the King",
  "A Horrible Way To Die",
  "A Night at the Opera",
  "A Nightmare On Elm Street",
  "A Quiet Place Part II",
  "A Room For Romeo Brass",
  "A Room With A View",
  "A Scene at the Sea",
  "A Ship Bound for India",
  "A Star Is Born (2018)",
  "A Tale of Two Sisters",
  "A Visitor to a Museum",
  "Ali: Fear Eats The Soul",
  "Alice Doesn’t Live Here Anymore",
  "An American Werewolf in London",
  "And The Ship Sails On",
  "Birdman",
  "Borgman",
  "Chi-raq",
  "Delicatessen",
  "Elephant",
  "Eternals",
  "Genova",
  "Hellraiser",
  "Holiday",
  "Humpday",
  "Krisha",
  "Lemonade",
  "Lolita",
  "Neruda",
  "Nikita",
  "Olivia",
  "Populaire",
  "Sidewalls",
  "Sideways",
  "Thelma",
  "Tideland",
  "Tristana",
  "Unbreakable",
  "Whiplash",
  "Wolfwalkers",
  "A Beautiful Day In The Neighborhood",
  "A Lizard In A Woman’s Skin",
  "A Quiet Place In The Country",
  "All Quiet on the Western Front",
  "An Evening With Beverly Luff Linn",
  "And The Fifth Horseman is Fear",
  "Austin Powers: International Man of Mystery",
  "Bullhead",
  "Chocolat",
  "Colossal",
  "Compliance",
  "Doomsday",
  "Entertainment",
  "Everyday",
  "Exotica",
  "Hermitage",
  "Julieta",
  "Moneyball",
  "Nocturama",
  "Nosferatu",
  "Persona",
  "Petulia",
  "Rebecca",
  "Rebecca",
  "Rosetta",
  "Sátántangó",
  "Secretary",
  "Siberia",
  "Superman",
  "Tiresia",
  "Underwater",
  "Beach Rats",
  "Beau Travail",
  "Black ’47",
  "Black Bear",
  "Black Book",
  "Black Christmas",
  "Black Jack",
  "Black Moon",
  "Black Mother",
  "Black Narcissus",
  "Black Panther",
  "Black Sabbath",
  "Black Snow",
  "Black Sunday",
  "Black Swan",
  "Black Widow",
  "Blade II",
  "Blade Runner",
  "Boarding Gate",
  "Charley Varrick",
  "Claire’s Camera",
  "Claire’s Knee",
  "Cuadecuc, Vampir",
  "Dead Man",
  "Dead Pigs",
  "Dead Ringers",
  "Dead Silence",
  "Deadpool 2",
  "Dear Wendy",
  "Death Note",
  "Death Proof",
  "Django Kill",
  "Django Unchained",
  "Flaming Star",
  "Flash Gordon",
  "Frances Ha",
  "Graduate First",
  "Graffiti Bridge",
  "Gran Torino",
  "Gray’s Anatomy",
  "Guava Island",
  "Heaven’s Gate",
  "Heavenly Creatures",
  "Ivan’s Childhood",
  "L.A. Confidential",
  "Mean Creek",
  "Mean Girls",
  "Mean Streets",
  "Near Dark",
  "Phantom Thread",
  "Rear Window",
  "Road Games",
  "Ryan’s Daughter",
  "Scarlet Diva",
  "Sea Fever",
  "Shallow Grave",
  "Shanghai Express",
  "Skate Kitchen",
  "Slack Bay",
  "Small Change",
  "Small Crimes",
  "Stalag 17",
  "Star Trek",
  "Star Wars",
  "Stardust Memories",
  "Starry Eyes",
  "Starship Troopers",
  "Training Day",
  "Trash Humpers",
  "Deliverance",
  "Dodes’ka-den",
  "Godzilla",
  "Hereditary",
  "Insomnia",
  "Lisztomania",
  "Midsommar",
  "Nightcrawler",
  "Performance",
  "Rocketman",
  "Suspiria",
  "Unstoppable",
  "Wonderland",
  "Wonderwall",
  "Yesterday",
  "Bad Boys II",
  "Ballad Of Narayama",
  "Batman & Robin",
  "Battle In Heaven",
  "Bay of Angels",
  "Calm With Horses",
  "Carnival of Souls",
  "Casa De Lava",
  "Catch Me Daddy",
  "Cathy Come Home",
  "Da 5 Bloods",
  "Dance Me Outside",
  "Dance of Reality",
  "Dances With Wolves",
  "Daniel Isn’t Real",
  "Daughters of Darkness",
  "Day for Night",
  "Days Of Heaven",
  "Dazed and Confused",
  "Eagle Vs. Shark",
  "Face to Face",
  "Fando y Lis",
  "Fanny and Alexander",
  "Fantastic Mr. Fox",
  "Far From Heaven",
  "Ganja & Hess",
  "Gate of Flesh",
  "Ham on Rye",
  "Happy Death Day",
  "Hard Core Logo",
  "Harold and Maude",
  "Jacquot de Nantes",
  "Kate Plays Christine",
  "La Dolce Vita",
  "La La Land",
  "La Pointe Courte",
  "Labyrinth of Passion",
  "Land of Plenty",
  "Last Flag Flying",
  "Law of Desire",
  "Lawrence Of Arabia",
  "Mad Max 2",
  "Made in U.S.A.",
  "Madonna and Child",
  "Magic Mike XXL",
  "Malcolm & Marie",
  "Man Of Steel",
  "Man on Fire",
  "Mary & Max",
  "Matthias & Maxime",
  "Natural Born Killers",
  "Pain and Gain",
  "Pain and Glory",
  "Paris Is Burning",
  "Paris, Je T’Aime",
  "Paths of Glory",
  "Saturday Night Fever",
  "Saving Private Ryan",
  "Sawdust and Tinsel",
  "Take Me Away!",
  "Take This Waltz",
  "Tale of Tales",
  "Tales From Earthsea",
  "Talk To Her",
  "Van Diemens Land",
  "Wake In Fright",
  "Walk The Line",
  "A Girl Walks Home Alone at Night",
  "A Good Woman Is Hard To Find",
  "Arabian Nights: Volume 2 The Desolate One",
  "Arabian Nights: Volume 3 The Enchanted One",
  "Cul-de-sac",
  "Goodfellas",
  "Journeyman",
  "Knife+Heart",
  "Phenomena",
  "Surveillance",
  "Cedar Rapids",
  "Cheap Thrills",
  "Edward II",
  "Edward Scissorhands",
  "Eika Katappa",
  "Female Trouble",
  "Final Girls",
  "Floating Weeds",
  "Gerald’s Game",
  "Great Expectations",
  "Human Highway",
  "I Vampiri",
  "Inland Empire",
  "Irma Vep",
  "Jurassic Park",
  "Jurassic World",
  "Logan Lucky",
  "Ocean’s Eleven",
  "Ocean’s Thirteen",
  "Piranha 3D",
  "Pola X",
  "Roman Holiday",
  "Strange Days",
  "Straw Dogs",
  "Stray Dog",
  "Total Recall",
  "Arabian Nights: Volume 1 – The Restless One",
  "Intervista",
  "Predestination",
  "Back to the Future",
  "Caltiki, The Immortal Monster",
  "Captain America: Civil War",
  "Casa De Mi Padre",
  "Castle in the Sky",
  "Dancer In The Dark",
  "Dawn of the Dead",
  "Day of the Dead",
  "Days Of Being Wild",
  "Falstaff (Chimes at Midnight)",
  "Fast & Furious 6",
  "Faster, Pussycat! Kill! Kill!",
  "Gangs of New York",
  "Insignificance",
  "Interstellar",
  "La Vie En Rose",
  "Lady in the Water",
  "Last and First Men",
  "Last Year at Marienbad",
  "Late August, Early September",
  "Mad Max Beyond Thunderdome",
  "Mad Max: Fury Road",
  "Man Is Not Bird",
  "Man On The Moon",
  "Man on the Roof",
  "Manchester by the Sea",
  "Maps to the Stars",
  "Margot At The Wedding",
  "Martha Marcy May Marlene",
  "Raise The Red Lantern",
  "Sanshiro Sugata Part II",
  "War of the Worlds",
  "Zazie Dans Le Métro",
  "A Glimpse Inside The Mind Of Charles Swan III",
  "A Pigeon Sat on a Branch Reflecting on Existence",
  "A Time To Love and A Time To Die",
  "Aguirre, The Wrath Of God (Aguirre, der Zorn Gottes)",
  "Bubba Ho-Tep",
  "Buffalo ’66",
  "Certain Women",
  "Elizabeth Harvest",
  "Ex Machina",
  "Extra Ordinary",
  "Les Amants",
  "Michael Clayton",
  "Michael Collins",
  "Mortal Transfer",
  "Mr. Arkadin",
  "On War",
  "Pineapple Express",
  "Private Life",
  "Scream 2",
  "Scream 3",
  "Scream 4",
  "Serial Mom",
  "Shiva Baby",
  "The A-Team",
  "The Aerial",
  "The American",
  "The Artist",
  "The Ascent",
  "The Assassin",
  "The Assistant",
  "The Avengers",
  "The Aviator",
  "Beatriz At Dinner",
  "Black Christmas (2019)",
  "Black is King",
  "Blade Runner 2049",
  "Blast Of Silence",
  "Bram Stoker’s Dracula",
  "Chained For Life",
  "Chariots Of Fire",
  "Crazy Rich Asians",
  "Dead Man Walking",
  "Dead Man’s Letters",
  "Dead Man’s Shoes",
  "Dead of Night",
  "Dead Poets Society",
  "Death and Transfiguration",
  "Death Becomes Her",
  "Death By Hanging",
  "Death In Venice",
  "Fear Of Fear",
  "Frankie and Johnny",
  "Heart of Glass",
  "Hearts Beat Loud",
  "I Am Cuba",
  "I Am Legend",
  "I Am Love",
  "Lean on Pete",
  "Leave No Trace",
  "Leaving Las Vegas",
  "Quantum of Solace",
  "Read My Lips",
  "Ready or Not",
  "Rhapsody in August",
  "Road To Perdition",
  "Stan & Ollie",
  "Stand By Me",
  "Star Trek Beyond",
  "Train To Busan",
  "What Happened Was…",
  "What Lies Beneath",
  "What Richard Did",
  "What’s Up, Doc?",
  "21 Grams",
  "45 Years",
  "Cinema Paradiso",
  "Cop Car",
  "Cry Baby",
  "Die Hard",
  "Due Date",
  "Elvira Madigan",
  "Everlasting Moments",
  "Girl Asleep",
  "Here Alone",
  "Highway 61",
  "Home Alone",
  "Immoral Tales",
  "Kick Ass",
  "Kid Galahad",
  "Lemonade Joe",
  "Les Carabiniers",
  "Rosemary’s Baby",
  "Russian Ark",
  "Russian Symphony",
  "Snow Angels",
  "Spy Game",
  "T2 Trainspotting",
  "The Babadook",
  "The Banishment",
  "The Cage",
  "The Canal",
  "The Canyons",
  "The Dancer",
  "The East",
  "The Fall",
  "The Falling",
  "The Farewell",
  "The Favourite",
  "The Garden",
  "The Hallow",
  "The Handmaiden",
  "The Hangover",
  "The Happening",
  "The Haunting",
  "The Ladykillers",
  "The Laundromat",
  "The Machinist",
  "The Magician",
  "The Martian",
  "The Mask",
  "The Master",
  "The Matrix",
  "The Party",
  "The Passenger",
  "The Raid",
  "The Rapture",
  "The Sacrament",
  "The Savages",
  "The Wailing",
  "The Walker",
  "The Wanderers",
  "The Warriors",
  "The Yards",
  "Too Late",
  "Back to the Future II",
  "Call Me By Your Name",
  "Can You Ever Forgive Me?",
  "Candyman: Farewell to the Flesh",
  "Captain America: The First Avenger",
  "Captain America: The Winter Soldier",
  "Catch Me If You Can",
  "Da Sweet Blood of Jesus",
  "Dawn of the Dead (2004)",
  "Fast Times at Ridgemont High",
  "Ga-Ga: Glory to the Heroes",
  "Happy New Year, Colin Burstead",
  "Hard To Be A God",
  "James and the Giant Peach",
  "Jane B. par Agnès V.",
  "La Belle et la Bête",
  "Lady Snowblood Song of Vengeance",
  "Lars And The Real Girl",
  "Last House on the Left",
  "Last Life in the Universe",
  "Man with a Movie Camera",
  "Raiders Of The Lost Ark",
  "Saw VII: The Final Chapter",
  "Tales from the Gimli Hospital",
  "12 Angry Men",
  "Breakfast On Pluto",
  "Breaking The Waves",
  "Escape from Alcatraz",
  "Godard Mon Amour",
  "Helas Pour Moi",
  "I Can’t Sleep",
  "I Want You",
  "In Another Country",
  "Invaders From Mars",
  "McCabe & Mrs.Miller",
  "Stranger Than Paradise",
  "Viva Las Vegas",
  "Voyage of Time",
  "Blue Jay",
  "Blue Valentine",
  "Brokeback Mountain",
  "Cloud Atlas",
  "Cold War",
  "Desperate Living",
  "Eden Lake",
  "Fish Tank",
  "Florida Man",
  "Fruitvale Station",
  "Good Favour",
  "Grey Gardens",
  "Hotel Artemis",
  "In Dreams",
  "Iron Man",
  "Jojo Rabbit",
  "Lili Marleen",
  "Nightmare Alley",
  "Nightmare Cinema",
  "Open Range",
  "Personal Shopper",
  "Pink Narcissus",
  "Red Beard",
  "Red Road",
  "Repo Man",
  "Rio Bravo",
  "Rio Grande",
  "Southland Tales",
  "Suburban Gothic",
  "The Beach",
  "The Beast",
  "The Claim",
  "The Craft",
  "The Graduate",
  "The Grandmaster",
  "The Pianist",
  "The Piano",
  "The Platform",
  "The Reader",
  "The Road",
  "The Searchers",
  "The Shallows",
  "Time Bandits",
  "Tomb Raider",
  "Tropical Malady",
  "Upstream Color",
  "Beasts of No Nation",
  "Brand Upon the Brain!",
  "Death Occurred Last Night",
  "Drag Me to Hell",
  "Guardians of the Galaxy",
  "Head Against The Wall",
  "Head of the Family",
  "Heartbeats (Les Amours Imaginaires)",
  "Planet of the Apes",
  "Planet of the Vampires",
  "Shadow of a Doubt",
  "Shadow of the Vampire",
  "Shaun Of The Dead",
  "Star Trek Into Darkness",
  "Team America: World Police",
  "Year Of The Dog",
  "Body Heat",
  "Brick Lane",
  "Dirty Dancing",
  "El Chicano",
  "Essential Killing",
  "Evil Dead",
  "Force Majeure",
  "Funny Games",
  "Funny Games",
  "Godzilla (1954)",
  "Hidden Agenda",
  "I, Tonya",
  "Intolerable Cruelty",
  "King Lear",
  "Les Créatures",
  "Mulholland Drive",
  "Nocturnal Animals",
  "Pet Sematary",
  "Pink Flamingos",
  "Prince Avalanche",
  "Ruby Sparks",
  "Seven Samurai",
  "Sexy Beast",
  "Speed Racer",
  "Suspiria (2018)",
  "The Departed",
  "The Dreamers",
  "The Getaway",
  "The Plea",
  "The Runaways",
  "The Stranger",
  "The Tenant",
  "The Trial",
  "Thor: Ragnarok",
  "Tone Deaf",
  "Veronika Voss",
  "White Material",
  "Back To The Future Part III",
  "Bad Times at the El Royale",
  "Band of Outsiders (Bande à part)",
  "Batman v Superman: Dawn of Justice",
  "Fall of the House of Usher",
  "Far From The Madding Crowd (1967)",
  "Far From The Madding Crowd (2015)",
  "Harry Potter and the Philosopher’s Stone",
  "La Peau Douce (The Soft Skin)",
  "Ladies and Gentlemen, the Fabulous Stains",
  "Pastoral To Die In The Country",
  "Pat Garrett & Billy The Kid",
  "Valerie & Her Week of Wonders",
  "28 Days Later",
  "Belladonna of Sadness",
  "Friday the 13th",
  "I Heart Huckabees",
  "I, Daniel Blake",
  "Mom and Dad",
  "My Darling Clementine",
  "One and Two",
  "The Adjustment Bureau",
  "The Alchemist Cookbook",
  "The Amazing Spider-Man",
  "The American Astronaut",
  "The American Friend",
  "The American Soldier",
  "The Angel’s Share",
  "The Angelic Conversation",
  "Blind Chance",
  "Dersu Uzala",
  "Donnie Darko",
  "Double Happiness",
  "Drunken Angel",
  "Gemini Man",
  "Hollow Man",
  "Hotel Transylvania",
  "House (Hausu)",
  "Jupiter Ascending",
  "Love Liza",
  "Murder Party",
  "Orchestra Rehearsal",
  "Pretty Baby",
  "Rescue Dawn",
  "Smiley Face",
  "Smokin’ Aces",
  "Sweet Charity",
  "The Cremator",
  "The Discarnates",
  "The Godfather",
  "The Leopard",
  "The Orphanage",
  "The Servant",
  "The Village",
  "True Romance",
  "White Heat",
  "Wild Strawberries",
  "2 Fast 2 Furious",
  "Cowards Bend The Knee",
  "I Care A Lot",
  "I Saw The Devil",
  "In a Glass Cage",
  "In a Lonely Place",
  "Invasion of Astro Monster",
  "Island of Lost Souls",
  "Jurassic World: Fallen Kingdom",
  "Lisa and The Devil",
  "Roman J. Israel, Esq.",
  "Selah and the Spades",
  "Stranger By The Lake",
  "Strangers on a Train",
  "We Are The Best!",
  "We Are The Night",
  "Beasts Of The Southern Wild",
  "Beauty and the Beast (1978)",
  "Brawl in Cell Block 99",
  "Charlie and The Chocolate Factory",
  "Clan of the Cave Bear",
  "Inauguration of the Pleasure Dome",
  "Seance on a Wet Afternoon",
  "Star Wars: The Force Awakens",
  "Star Wars: The Last Jedi",
  "That Obscure Object of Desire",
  "What’s the Matter with Helen?",
  "Bad Lieutenant: Port Of Call New Orleans",
  "Dawn of the Planet of the Apes",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and The Half Blood Prince",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban",
  "Nausicaä of the Valley of the Wind",
  "Salò, or the 120 Days of Sodom",
  "Talladega Nights: The Ballad of Ricky Bobby",
  "War for the Planet of the Apes",
  "Big Bad Wolves",
  "Burn After Reading",
  "Come and See",
  "Dog Eat Dog",
  "Guys and Dolls",
  "High and Low",
  "Love and Friendship",
  "Messiah of Evil",
  "Mothra Vs Godzilla",
  "My Beautiful Laundrette",
  "Odd Man Out",
  "Rio Das Mortes",
  "Rust And Bone",
  "The Bad Batch",
  "The Band Wagon",
  "The Damned United",
  "The Danish Girl",
  "The Darjeeling Limited",
  "The Dark Knight",
  "The Day After",
  "The Hateful Eight",
  "The Lady Eve",
  "The Last Battle",
  "The Last Command",
  "The Last Detail",
  "The Last Metro",
  "The Mad Hatter",
  "The Magic Flute",
  "The Magnificent Ambersons",
  "The Maltese Falcon",
  "The Matrix Reloaded",
  "The Matrix Revolutions",
  "The Pact II",
  "The Parallax View",
  "The Raid 2",
  "The Rainbow Thief",
  "The Tango Lesson",
  "Two Lane Blacktop",
  "Wild At Heart",
  "Bright Star",
  "Citizen Kane",
  "Don’t Breathe",
  "Down Terrace",
  "Eighth Grade",
  "Ginger Snaps",
  "Jimmy’s Hall",
  "Kissing Candice",
  "Les Misérables",
  "Mistress America",
  "Morvern Callar",
  "Pete’s Dragon",
  "Spirited Away",
  "The Birdcage",
  "The Fountain",
  "The Invitation",
  "The Mountain",
  "The Revenant",
  "Toni Erdmann",
  "TRON: Legacy",
  "Harry Potter and The Deathly Hallows Part 1",
  "Harry Potter and The Deathly Hallows Part 2",
  "Harry Potter and The Order of the Phoenix",
  "Mauvais Sang (Bad Blood) (The Night Is Young)",
  "Pauline At the Beach (Pauline à la plage)",
  "Valerian and the City of a Thousand Planets",
  "Brigsby Bear",
  "Child’s Play",
  "Cold Mountain",
  "Crimson Peak",
  "Doctor Strange",
  "Greener Grass",
  "Jeux d’Enfants",
  "Justice League",
  "Lost Highway",
  "Millenium Actress",
  "Multiple Maniacs",
  "Mystery Team",
  "Mystery Train",
  "New Nightmare",
  "Pretty Woman",
  "Promised Land",
  "Revolutionary Road",
  "Spring Breakers",
  "The Criminal",
  "The Homesman",
  "The Hurricane",
  "The Immigrant",
  "The Immortals",
  "The Informant!",
  "The Irishman",
  "The Proposal",
  "The Survivalist",
  "The Terminator",
  "Wonder Woman",
  "Cool Hand Luke",
  "Cries and Whispers",
  "Five Easy Pieces",
  "Iron Man 2",
  "Iron Man 3",
  "Swiss Army Man",
  "The Beach Bum",
  "The Black Dahlia",
  "The Blackcoat’s Daughter",
  "The Dead Zone",
  "The Heart Machine",
  "The Phantom Carriage",
  "The Piano Teacher",
  "The Roaring Twenties",
  "The Scarlet Letter",
  "The Shawshank Redemption",
  "The Station Agent",
  "The Tracey Fragments",
  "Tout Va Bien",
  "Wendy and Lucy",
  "Zero Dark Thirty",
  "30 Days of Night",
  "Distant Voices, Still Lives",
  "Embrace Of The Serpent",
  "Fox and His Friends",
  "I Trapped The Devil",
  "It Happened One Night",
  "Message From The King",
  "Sympathy for Mr. Vengeance",
  "The ABCs of Death",
  "The Abominible Dr. Phibes",
  "The Age of Innocence",
  "The Annihilation of Fish",
  "The Army of Shadows",
  "Tom at the Farm",
  "Dracula: Pages from a Virgin’s Diary",
  "Fear and Loathing In Las Vegas",
  "Guardians of the Galaxy Vol. 2",
  "I Am Not a Serial Killer",
  "Beware Of A Holy Whore",
  "I Want To Go Home",
  "In A Valley of Violence",
  "Judas and the Black Messiah",
  "Stranger on the Third Floor",
  "Broken Embraces",
  "Doctor Zhivago",
  "Dom Hemingway",
  "Fellini’s Casanova",
  "Forbidden Games",
  "Groundhog Day",
  "Johnny Guitar",
  "Shutter Island",
  "Sleeping Beauty",
  "Someone Great",
  "Suicide Squad",
  "The Conversation",
  "The Descendants",
  "The Underneath",
  "The Untouchables",
  "Berberian Sound Studio",
  "Bonnie And Clyde",
  "Coffee and Cigarettes",
  "Crimes and Misdemeanors",
  "Drop Dead Gorgeous",
  "Evil Dead II",
  "F for Fake",
  "First Name: Carmen",
  "Kill, Baby Kill",
  "Nymphomaniac Vol 1",
  "Nymphomaniac Vol 2",
  "Run Lola Run",
  "Super Dark Times",
  "The Breakfast Club",
  "The Coca-Cola Kid",
  "The Disaster Artist",
  "The Greasy Strangler",
  "The Great Beauty",
  "The Great Dictator",
  "The Great Gatsby",
  "The Great Silence",
  "The Miracle Worker",
  "The Polar Express",
  "The Royal Tenenbaums",
  "The Straight Story",
  "The Strange Ones",
  "The Usual Suspects",
  "Vivre Sa Vie",
  "Z for Zachariah",
  "Pretty Persuasion",
  "The Nightingale",
  "Velvet Buzzsaw",
  "Vivement Dimanche",
  "12 Years A Slave",
  "500 Days of Summer",
  "Che Part 2 (Guerrilla)",
  "Dumb and Dumber To",
  "Funeral Parade of Roses",
  "It's a Wonderful Life",
  "Much Ado About Nothing",
  "Our Day Will Come",
  "The Bad Sleep Well",
  "The Dark Knight Rises",
  "The Da Vinci Code",
  "The Day He Arrives",
  "The Day Shall Come",
  "The Hands of Orlac",
  "The Hangover Part II",
  "The Hangover Part III",
  "The Lady from Shanghai",
  "The Last of England",
  "The Last Picture Show",
  "The Man From London",
  "The Man Who Cried",
  "The Man Who Laughs",
  "The Manchurian Candidate (2004)",
  "The Passion of Anna",
  "The Talented Mr. Ripley",
  "The Taste of Tea",
  "The Vast of Night",
  "The War of Jan-Ken-Pon",
  "Scary Stories to Tell in the Dark",
  "What Have I Done To Deserve This?",
  "Bed & Board",
  "Destroy All Monsters",
  "Full Metal Jacket",
  "He Got Game",
  "Kustom Kar Kommandos",
  "Observe And Report",
  "Son of Saul",
  "The Imitation Game",
  "The Indian Runner",
  "The Niklashausen Journey",
  "The Social Network",
  "The Truman Show",
  "Inglourious Basterds",
  "London Boulevard",
  "Sunset Boulevard",
  "White Christmas",
  "Ebirah Horror of the Deep",
  "For A Few Dollars More",
  "Friday the 13th Part 2",
  "Friday the 13th Part III",
  "It Rains On Our Love",
  "The Adventures Of Baron Munchausen",
  "The Adventures of Robin Hood",
  "The Arrival of Joachim Stiller",
  "The Art of Self Defence",
  "The Assassination of Richard Nixon",
  "The Autopsy of Jane Doe",
  "Who Are You, Polly Maggoo?",
  "You Ain’t Seen Nothin’ Yet",
  "In A Year Of Thirteen Moons",
  "My American Uncle (Mon oncle d’Amérique)",
  "2001: A Space Odyssey",
  "Blood And Black Lace",
  "Bunny and the Bull",
  "Electra Glide In Blue",
  "Snow Falling on Cedars",
  "Terminator 2: Judgement Day",
  "The Beaches of Agnès",
  "The Dead Don’t Die",
  "The Death of Stalin",
  "The Fearless Vampire Killers",
  "The Grand Budapest Hotel",
  "The Grapes of Wrath",
  "The Peanut Butter Falcon",
  "The Sea of Trees",
  "The Shape of Water",
  "The State of Things",
  "When Harry Met Sally...",
  "Who Framed Roger Rabbit",
  "Y Tu Mamá También",
  "Midnight Special",
  "Queen Christina",
  "Werckmeister Harmonies",
  "Bob le Flambeur",
  "By The Sea",
  "Come To Daddy",
  "Down By Law",
  "Kung Fu Master!",
  "Louder Than Bombs",
  "Men in Black",
  "O Lucky Man!",
  "On The Beach",
  "On The Road",
  "Port of Call",
  "The Elephant Man",
  "The Mothman Prophecies",
  "The Spectacular Now",
  "Un Chien Andalou",
  "Yourself and Yours",
  "Jeanne Dielman, 23, quai du commerce, 1080 Bruxelles",
  "Quackser Fortune Has a Cousin in the Bronx",
  "Star Wars: Episode I – The Phantom Menace",
  "Slumdog Millionaire",
  "Bill and Ted’s Bogus Journey",
  "Bill and Ted’s Excellent Adventure",
  "Che Part 1 (The Argentine)",
  "If Beale Street Could Talk",
  "Invocation of My Demon Brother",
  "Kubo and the Two Strings",
  "Our Lady of the Turks",
  "The Bad and the Beautiful",
  "The Ballad of Buster Scruggs",
  "The Ballad of Cable Hogue",
  "The Cabin In The Woods",
  "The Cabinet of Dr. Caligari",
  "The Face of an Angel",
  "The Fast and the Furious",
  "The Last Days On Mars",
  "The Last of the Mohicans",
  "The Last Temptation Of Christ",
  "The Man Who Loved Women",
  "The Man Who Wasn’t There",
  "The Marriage of Maria Braun",
  "The Panic in Needle Park",
  "The Passion of the Christ",
  "BPM (Beats Per Minute)",
  "Dementia (Daughter of Horror)",
  "Even Dwarfs Started Small",
  "Free State of Jones",
  "Mickey and the Bear",
  "Never Rarely Sometimes Always",
  "Picnic at Hanging Rock",
  "The Gleaners & I",
  "The Texas Chainsaw Massacre",
  "The Wizard Of Oz",
  "The Woman in Black",
  "The Woman Next Door",
  "Before I Wake",
  "Buster’s Mal Heart",
  "Child’s Play (2019)",
  "Child’s Play 2",
  "Child’s Play 3",
  "Dinner in America",
  "From The East",
  "Fruit of Paradise",
  "Go Down Death",
  "God Bless America",
  "Gretel & Hansel",
  "Hold The Dark",
  "Life is Beautiful",
  "Lords Of Salem",
  "Lost in Translation",
  "Milou en Mai",
  "Music in Darkness",
  "Night on Earth",
  "Queen of Earth",
  "Song of Granite",
  "The 13th Warrior",
  "The Big Trail",
  "The Blue Lamp",
  "The Florida Project",
  "The Immortal Story",
  "The Lone Ranger",
  "The Wolf Man",
  "Me and You and Everyone We Know",
  "Pirates of the Caribbean: At World’s End",
  "Pirates of the Caribbean: Dead Man’s Chest",
  "Pirates of the Caribbean: On Stranger Tides",
  "Friday the 13th: The Final Chapter",
  "I Stand Alone (Seul Contre Tous)",
  "I’m A Cyborg, But That’s Okay",
  "Indiana Jones and the Last Crusade",
  "It Happened At The World’s Fair",
  "Star Wars: Episode II – Attack of the Clones",
  "Star Wars: Episode III – Revenge of the Sith",
  "Mississippi Mermaid",
  "Bride of Reanimator",
  "Eloge de L’amour",
  "Everybody Wants Some!!",
  "Fellini – Satyricon",
  "Ford V Ferrari",
  "Kill Your Darlings",
  "Life of Brian",
  "Nights of Cabiria",
  "Only The Brave",
  "Post Tenebras Lux",
  "Punisher: War Zone",
  "River of Grass",
  "Suddenly, Last Summer",
  "Summer of Sam",
  "The Green Ray",
  "The Hired Hand",
  "The Iron Giant",
  "The Most Beautiful",
  "The Moth Diaries",
  "The Purge: Anarchy",
  "The Third Man",
  "The Ugly Swans",
  "Une Femme Mariée",
  "20,000 Days on Earth",
  "But I’m A Cheerleader",
  "In The Tall Grass",
  "L’une Chante, l’Autre Pas",
  "On Body and Soul",
  "The Company of Wolves",
  "The Godfather Part II",
  "The Thomas Crown Affair",
  "Through A Glass Darkly",
  "Tinker Tailor Soldier Spy",
  "To Kill A Mockingbird",
  "Wish I Was Here",
  "Ghidorah The Three Headed Monster",
  "Girl Walks Into a Bar",
  "Solo: A Star Wars Story",
  "The Death of Dick Long",
  "The Death of Maria Malibran",
  "The Imaginarium of Doctor Parnassus",
  "The Phantom of the Opera",
  "The Place Beyond The Pines",
  "Who’s Afraid Of Virginia Woolf?",
  "Witchfinder General",
  "On A Clear Day You Can See Forever",
  "I Am The Pretty Thing That Lives In The House",
  "Behind The Candelabra",
  "Being John Malkovich",
  "Blood For Dracula",
  "Def By Temptation",
  "Enter The Dragon",
  "Flesh For Frankenstein",
  "For Ever Mozart",
  "Ginger & Rosa",
  "I’m Your Woman",
  "Little Big Man",
  "Love Unto Death",
  "Melvin & Howard",
  "Simon, The Magician",
  "Sound of Metal",
  "The Crying Game",
  "The Devils Backbone",
  "The Fourth Man",
  "The Hunger Games",
  "The Silent Partner",
  "The Wicker Man",
  "This Is England",
  "Trick ‘R Treat",
  "Under The Shadow",
  "Eternal Sunshine of The Spotless Mind",
  "Portrait of a Lady on Fire",
  "The Day the Earth Stood Still",
  "The Lair of the White Worm",
  "The Man Who Fell To Earth",
  "The Man Who Killed Don Quixote",
  "The Man Who Knew Too Much",
  "The Masque of the Red Death",
  "The Passion of Joan of Arc",
  "The Saddest Music in the World",
  "Elevator To The Gallows (Ascenseur pour l’échafaud)",
  "Indiana Jones and the Temple of Doom",
  "24 Hour Party People",
  "Birth of a Nation",
  "Goto, Island of Love",
  "It Comes at Night",
  "Let Them All Talk",
  "Roselyne and the Lions",
  "World On A Wire",
  "Godzilla: King of the Monsters",
  "Hedwig and the Angry Inch",
  "The Strangers: Prey at Night",
  "The Texas Chainsaw Massacre 2",
  "Three Days of the Condor",
  "E.T. The Extra-Terrestrial",
  "Le Bonheur (Happiness)",
  "Le Petit Soldat",
  "Life During Wartime",
  "Soldier of Orange",
  "The English Patient",
  "The Good German",
  "V for Vendetta",
  "Bell Book and Candle",
  "Blow The Man Down",
  "Hobo With A Shotgun",
  "Sex, Lies And Videotape",
  "Syndromes and a Century",
  "The Long Day Closes",
  "The Nightmare Before Christmas",
  "The Truth About Charlie",
  "Mishima: A Life in Four Chapters",
  "The Black Book (Reign of Terror)",
  "The Diary of a Teenage Girl",
  "House of Tolerance",
  "Pee-Wee’s Big Adventure",
  "Son of Godzilla",
  "Terror of Mechagodzilla",
  "The Burning Plain",
  "The Holy Mountain",
  "The Little Stranger",
  "The Selfish Giant",
  "The Seventh Seal",
  "The Sweet Hereafter",
  "71 Fragments of a Chronology of Chance",
  "Fur: An Imaginary Portrait Of Diane Arbus",
  "The Last Black Man in San Francisco",
  "The War of the Worlds: Next Century",
  "How to Marry a Millionaire",
  "Let’s Scare Jessica To Death",
  "My Life as a Zucchini",
  "The Pit and The Pendulum",
  "The Portait of a Lady",
  "The Unbearable Lightness of Being",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Buffy the Vampire Slayer",
  "Emperor Tomato Ketchup (Short)",
  "Kiss Kiss Bang Bang",
  "My Own Private Idaho",
  "The Umbrellas Of Cherbourg",
  "Thor: The Dark World",
  "Howl’s Moving Castle",
  "Inside Llewyn Davis",
  "Kong: Skull Island",
  "Resident Evil: Afterlife",
  "Resident Evil: Apocalypse",
  "Sleepless in Seattle",
  "The Crossing Guard",
  "The Monster Squad",
  "The Suicide Squad",
  "The Third Generation",
  "The Wormwood Star",
  "Trouble Every Day",
  "Butch Cassidy and the Sundance Kid",
  "The Disappearance of Eleanor Rigby: Her",
  "The Disappearance of Eleanor Rigby: Him",
  "Twin Peaks: Fire Walk With Me",
  "Yi-Yi (A One and A Two)",
  "Roy Colt and Winchester Jack",
  "The Enigma Of Kaspar Hauser",
  "The Postman Always Rings Twice",
  "The Two Faces of January",
  "Nosferatu the Vampyre (Nosferatu Phantom Der Nacht)",
  "The Heart Is Deceitful Above All Things",
  "The Day a Pig Fell Into the Well",
  "I Live In Fear",
  "Out of the Past",
  "Requiem For A Dream",
  "Scenes from a Marriage",
  "The Wheel (La Roue)",
  "10 Cloverfield Lane",
  "They Were Expendable",
  "Life Is A Bed of Roses",
  "Seven Stages to Achieve Eternal Bliss",
  "The Extraordinary Adventures of Adèle Blanc-Sec",
  "The Private Life of Sherlock Holmes",
  "To Live and Die in L.A.",
  "Who’s That Knocking At My Door",
  "Girl with a Pearl Earring",
  "Puzzle of a Downfall Child",
  "Smiles Of A Summer Night",
  "The Girl Can’t Help It",
  "The Hunchback of Notre Dame",
  "The Quick and the Dead",
  "The Squid and the Whale",
  "Broken Circle Breakdown",
  "Silver Linings Playbook",
  "Summer with Monika",
  "The Devil’s Doorway",
  "The Invisible Woman",
  "The Whispering Star",
  "Beyond The Black Rainbow",
  "Childhood of a Leader",
  "Dogs Don’t Wear Pants",
  "Down In The Valley",
  "Eyes Without A Face",
  "Four Times that Night",
  "John Wick: Chapter 2",
  "Kiss of the Damned",
  "The Slumber Party Massacre",
  "Buffalo Bill and the Indians, or Sitting Bull’s History Lesson",
  "Les Amants Du Pont Neuf (The Lovers on the Bridge)",
  "The Assassination Of Jesse James By The Coward Robert Ford",
  "The Iguana with the Tongue of Fire",
  "The Strange Colour of Your Body’s Tears",
  "The Man Who Killed Hitler and Then the Bigfoot",
  "The Death and Life of John F. Donovan",
  "Throw Away Your Books, Rally in the Streets",
  "One Wonderful Sunday",
  "Dr. Jekyll and Mr. Hyde",
  "Freddy’s Dead: The Final Nightmare",
  "Good Night And Good Luck",
  "Snow White and The Huntsman",
  "The Hills Have Eyes (2006)",
  "The Miseducation of Cameron Post",
  "The Night Eats the World",
  "Don’t Torture A Duckling",
  "Gods Of The Plague",
  "Hell or High Water",
  "Knife In The Water",
  "Kumiko the Treasure Hunter",
  "Meshes of the Afternoon",
  "Rebel Without A Cause",
  "The Thief of Paris",
  "The Twilight Saga: Eclipse",
  "In The Heart of the Sea",
  "The Life Aquatic With Steve Zissou",
  "The Merchant Of The Four Seasons",
  "The Old Man & The Gun",
  "Promising Young Woman",
  "The Threepenny Opera",
  "Chitty Chitty Bang Bang",
  "One From The Heart",
  "Out of the Furnace",
  "The Bride of Frankenstein",
  "The Curse of Frankenstein",
  "The Midnight Meat Train",
  "One Hundred and One Nights",
  "The Girl on a Motorcycle",
  "The House That Jack Built",
  "Love Affair, or the Case of the Missing Switchboard Operator",
  "Once Upon A Time In America",
  "Once Upon a Time in Anatolia",
  "Once Upon a Time… In Hollywood",
  "The Personal History of David Copperfield",
  "Willy Wonka and the Chocolate Factory",
  "Léon: The Professional",
  "Clouds of Sils Maria",
  "Colour Out of Space",
  "Dolemite Is My Name",
  "Legends of the Fall",
  "Murmur of the Heart",
  "Pink Floyd The Wall",
  "Singin’ in the Rain",
  "The Deep Blue Sea",
  "The Horror of Frankenstein",
  "The Kingdom of Naples",
  "The Long Dumb Road",
  "The Witches of Eastwick",
  "300: Rise of an Empire",
  "Blue Is The Warmest Colour",
  "The Belly of an Architect",
  "The King Of Marvin Gardens",
  "The Story of Adele H",
  "The Wolf of Wall Street",
  "To The Devil a Daughter",
  "O-Bi, O-Ba – The End of Civilisation",
  "Rogue One: A Star Wars Story",
  "The Best Years of Our Lives",
  "The Wind That Shakes the Barley",
  "Everything Is Illuminated",
  "Mirror (Зеркало, Zerkalo)",
  "Pokémon Detective Pikachu",
  "Dr. Phibes Rises Again",
  "House of Flying Daggers",
  "Let The Corpses Tan",
  "Only Lovers Left Alive",
  "Something in the Air",
  "Tetsuo II: Body Hammer",
  "The Revenge of Frankenstein",
  "The Strange Case of Dr. Jekyll and Miss Osbourne",
  "I Think We’re Alone Now",
  "The Blood on Satan’s Claw",
  "The Twilight Saga: New Moon",
  "White Bird in a Blizzard",
  "Lone Wolf and Cub: Sword of Vengeance",
  "Once Upon A Time In The West",
  "Sin City: A Dame to Kill For",
  "5 Dolls for an August Moon",
  "We Need To Talk About Kevin",
  "Bend It Like Beckham",
  "Ferris Bueller's Day Off",
  "Fighting With My Family",
  "Mysterious Object at Noon",
  "Tetsuo: The Iron Man",
  "The Comfort of Strangers",
  "The Trouble With Harry",
  "Under The Silver Lake",
  "My Night At Maud’s (Ma Nuit Chez Maud)",
  "Come Back to the 5 & Dime Jimmy Dean, Jimmy Dean",
  "Confessions of a Dangerous Mind",
  "The Legend Of Kaspar Hauser",
  "The Wind Will Carry Us",
  "Dr. Goldfoot and the Girl Bombs",
  "It’s Kind Of A Funny Story",
  "Monty Python and the Holy Grail",
  "The Curious Case Of Benjamin Button",
  "Bringing Out The Dead",
  "Where’d You Go Bernadette",
  "The Horrors of Malformed Men",
  "The People vs. Larry Flint",
  "The Secret Of Roan Inish",
  "Lone Wolf and Cub: Baby Cart in Peril",
  "Lone Wolf and Cub: Baby Cart to Hades",
  "Lone Wolf and Cub: White Heaven in Hell",
  "Interview With The Vampire",
  "The Colour of Pomegranates",
  "The Empire Strikes Back",
  "The Girl With All The Gifts",
  "The Three Burials of Melquiades Estrada",
  "In The Mouth of Madness",
  "Love Is Colder Than Death",
  "O Brother, Where Art Thou?",
  "The Brother From Another Planet",
  "You Were Never Really Here",
  "The Light Between Oceans",
  "The Return of Godzilla",
  "The Killing of a Sacred Deer",
  "The Bitter Tears Of Petra Von Kant",
  "Repo! The Genetic Opera",
  "The Notorious Bettie Page",
  "The Purge: Election Year",
  "Lone Wolf: Baby Cart at the River Styx",
  "Shoot The Piano Player (Tirez Sur Le Pianiste)",
  "The Diving Bell and the Butterfly",
  "Rise of the Planet of the Apes",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "Mission: Impossible – Fallout",
  "The Secret of the Grain",
  "The Silence Of The Lambs",
  "Bring Me The Head of Alfredo Garcia",
  "The Good, The Bad And The Ugly",
  "Gremlins 2: The New Batch",
  "The Twilight Saga: Breaking Dawn – Part 1",
  "The Twilight Saga: Breaking Dawn – Part 2",
  "Lone Wolf and Cub: Baby Cart in the Land of Demons",
  "Ghost Dog: The Way of the Samurai",
  "In The Presence of a Clown",
  "The Perks of Being A Wallflower",
  "À Bout De Souffle (Breathless)",
  "Night of the Living Dead",
  "Resident Evil: The Final Chapter",
  "The Bride With White Hair",
  "Where The Wild Things Are",
  "Crouching Tiger, Hidden Dragon",
  "Decline of Western Civilization",
  "Kings of the Road (Im Lauf der Zeit)",
  "The Men Who Tread on the Tigers Tail",
  "Love In The Afternoon (Chloe In The Afternoon) (L’amour l’après-midi)",
  "Ghosts… Of The Civil Dead",
  "Hellboy II: The Golden Army",
  "The Girl With The Dragon Tattoo",
  "The Lost Honour of Katharina Blum",
  "The Secret Life of Walter Mitty",
  "Pepi, Luci, Bom and Other Girls Like Mom",
  "WR: Mysteries of the Organism",
  "Mother Kusters Goes To Heaven",
  "From the Life of the Marionettes",
  "My Son, My Son, What Have Ye Done?",
  "Uncle Boonme Who Can Recall His Past Lives",
  "Big Trouble in Little China",
  "History of the World: Part 1",
  "The 1,000 Eyes of Dr. Mabuse",
  "The Bird With The Crystal Plumage",
  "The Return of the Prodigal Son",
  "Mission: Impossible – Rogue Nation",
  "Young Person’s Guide to Cinema",
  "I Killed My Mother (J’ai tué ma mère)",
  "Women on the Verge of a Nervous Breakdown",
  "True History of the Kelly Gang",
  "The Meyerowitz Stories (New and Selected)",
  "Sweeney Todd: The Demon Barber of Fleet Street",
  "Slow Motion (Every Man for Himself) (Sauve Que Peut (La Vie)",
  "The Hitchhiker’s Guide To The Galaxy",
  "Don’t Worry He Won’t Get Far On Foot",
  "Successive Slidings of Pleasure (Glissements progressifs du plaisir)",
  "Miss Peregrine’s Home for Peculiar Children",
  "Extremely Wicked, Shockingly Evil and Vile",
  "Une Femme Est Une Femme (A Woman Is a Woman)",
  "Two or Three Things I Know About Her (2 ou 3 choses que je sais d’elle)",
  "Get The Gringo (How I Spent My Summer Vacation)",
];
